name: Auth Health Check

on:
  #schedule:
  #  - cron: 0 0 0 0 1
  workflow_dispatch:

jobs:
  khu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: curl
        uses: wei/curl@master
        with:
          args: https://portal.khu.ac.kr/ksign/index.jsp

      - name: Install dependencies
        run: |
          pip install -e src/

      - name: Healthcheck for khu auth
        run:
          python src/tests/khu.py ${{ secrets.TEST_KHU_USERNAME}} ${{ secrets.TEST_KHU_PASSWORD }} > /dev/null
